Greeting.create(message: "Hello!")
Greeting.create(message: "Hi there! You good today?")
Greeting.create(message: "Greetings! How are you?")
Greeting.create(message: "Welcome, friend!")
Greeting.create(message: "Good day, Micronauts!")